// Generated by python -m app.export_contract. Do not edit by hand.

// Decimal output values are exact strings; input duration is a JSON number.

export type CalendarWindow = {
  "start": string;
  "end": string;
};

export type CatalogDictionaries = {
  "city": Array<string>;
  "categories": Array<string>;
  "event_formats": Array<string>;
  "languages": Array<string>;
};

export type CatalogMetadata = {
  "status": "ready";
  "catalog_version": string;
  "source_sha256": string;
  "origin": "original" | "team" | "demo";
  "profile_count": number;
  "calendar": CalendarWindow;
  "dictionaries": CatalogDictionaries;
  "quality": QualityStats;
  "city_counts": {
  [key: string]: number;
};
  "category_counts": {
  [key: string]: number;
};
};

export type DataWarning = {
  "code": string;
  "message": string;
  "evidence"?: (Evidence | null);
  "profile_id"?: (string | null);
};

export type ErrorIssue = {
  "field": string;
  "message": string;
};

export type ErrorResponse = {
  "code": "INVALID_QUERY" | "CATALOG_LOAD_FAILED" | "INTERNAL_ERROR";
  "message": string;
  "issues"?: Array<ErrorIssue>;
};

export type Evidence = {
  "code": string;
  "field": string;
  "profile_value"?: (string | number | boolean | Array<string> | null);
  "requested_value"?: (string | number | boolean | Array<string> | null);
  "quote"?: (string | null);
  "text": string;
  "display_is_cleaned"?: boolean;
};

export type Exclusion = {
  "id": string;
  "reasons": Array<"BUSY_ON_DATE" | "UNSUPPORTED_FORMAT" | "OVER_BUDGET" | "UNSUPPORTED_LANGUAGE" | "DURATION_EXCEEDED">;
  "primary_reason": "BUSY_ON_DATE" | "UNSUPPORTED_FORMAT" | "OVER_BUDGET" | "UNSUPPORTED_LANGUAGE" | "DURATION_EXCEEDED";
};

export type HealthResponse = {
  "status": "ready";
  "profile_count": number;
  "catalog_version": string;
};

export type MatchCounts = {
  "group": number;
  "matched": number;
  "shown": number;
};

export type QualityStats = {
  "synthetic": number;
  "city_imputed": number;
  "price_imputed": number;
  "null_max_hours": number;
};

export type RecommendationCard = {
  "id": string;
  "anon_name": string;
  "category": string;
  "categories": Array<string>;
  "city": string;
  "price_from_kzt": number;
  "price_label": string;
  "event_date": string;
  "availability_text": string;
  "languages": Array<string>;
  "max_hours": (string | null);
  "duration_text": string;
  "explanation": string;
  "evidence": Array<Evidence>;
  "synthetic": boolean;
  "city_imputed": boolean;
  "price_imputed": boolean;
  "origin": "original" | "team" | "demo";
  "labels": Array<string>;
  "warnings": Array<DataWarning>;
};

export type RecommendationQuery = {
  "city": string;
  "event_date": string;
  "event_format": string;
  "category": string;
  "budget_kzt": number;
  "duration_hours"?: (string | null);
  "language"?: (string | null);
};

export type RecommendationRequest = {
  "city": string;
  "event_date": string;
  "event_format": string;
  "category": string;
  "budget_kzt": number;
  "duration_hours"?: (number | string | null);
  "language"?: (string | null);
};

export type RecommendationResponse = {
  "status": "MATCHED" | "CATEGORY_UNAVAILABLE" | "NO_MATCHES";
  "message": string;
  "query": RecommendationQuery;
  "catalog_version": string;
  "ranking_version": string;
  "explanation_version": string;
  "counts": MatchCounts;
  "rejections": {
  [key: string]: number;
};
  "cards": Array<RecommendationCard>;
  "warnings": Array<DataWarning>;
  "eligible_ids": Array<string>;
  "exclusions": Array<Exclusion>;
};
