import { randomUUID } from 'node:crypto'
import { expect, test, type Page } from '@playwright/test'

const password = 'Событие для друзей 2026!'
const accountDialog = (page: Page) => page.getByRole('dialog')
test.setTimeout(45_000)

async function openAccount(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Войти в аккаунт', exact: true }).click()
  await expect(accountDialog(page)).toBeVisible()
}

async function register(page: Page, email: string, capture = false) {
  const dialog = accountDialog(page)
  await dialog.getByRole('button', { name: 'Регистрация', exact: true }).click()
  await dialog.getByLabel('Имя', { exact: true }).fill('Айдана')
  await dialog.getByLabel('Email', { exact: true }).fill(email)
  await dialog.getByLabel('Пароль', { exact: true }).fill(password)
  await dialog.getByLabel('Город', { exact: false }).fill('Алматы')
  if (capture) await page.screenshot({ path: '/tmp/ai-ana-account-register-desktop.png' })
  await dialog.getByRole('button', { name: 'Создать аккаунт', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: 'Ваш профиль' })).toBeVisible({ timeout: 15_000 })
}

test('регистрация, изменение профиля, восстановление сессии, выход и повторный вход', async ({ page, context }) => {
  const email = `account-${randomUUID()}@example.com`
  await openAccount(page)
  await register(page, email, true)
  const dialog = accountDialog(page)
  await expect(dialog.getByLabel('Email', { exact: true })).toHaveValue(email)
  await expect(dialog.getByLabel('Email', { exact: true })).toHaveAttribute('readonly', '')
  await dialog.getByLabel('Имя', { exact: true }).fill('Айдана Серик')
  await dialog.getByLabel('Город', { exact: false }).fill('Астана')
  await dialog.getByRole('button', { name: 'Сохранить изменения' }).click()
  await expect(dialog.getByRole('status')).toHaveText('Профиль сохранён.')
  await page.screenshot({ path: '/tmp/ai-ana-account-profile-desktop.png' })
  const cookies = await context.cookies()
  expect(cookies.some(cookie => cookie.httpOnly && cookie.sameSite === 'Lax')).toBeTruthy()
  expect(await page.evaluate(() => Object.values(localStorage).some(value => String(value).includes('csrf_token') || String(value).includes('password')))).toBeFalsy()
  await page.reload()
  await page.getByRole('button', { name: 'Профиль: Айдана Серик' }).click()
  await expect(dialog.getByLabel('Имя', { exact: true })).toHaveValue('Айдана Серик')
  await expect(dialog.getByLabel('Город', { exact: false })).toHaveValue('Астана')
  await dialog.getByRole('button', { name: 'Выйти из аккаунта' }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Войти в аккаунт' })).toBeFocused()
  await page.reload()
  await page.getByRole('button', { name: 'Войти в аккаунт' }).click()
  await dialog.getByLabel('Email', { exact: true }).fill(email)
  await dialog.getByLabel('Пароль', { exact: true }).fill(password)
  await dialog.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: 'Ваш профиль' })).toBeVisible({ timeout: 15_000 })
  await expect(dialog.getByLabel('Город', { exact: false })).toHaveValue('Астана')
  await dialog.getByRole('button', { name: 'Выйти из аккаунта' }).click()
})

test('проверки формы и неверный пароль показывают ошибки, подбор доступен гостю', async ({ page }) => {
  let registrationRequests = 0
  page.on('request', request => { if (request.url().endsWith('/api/auth/register')) registrationRequests++ })
  await openAccount(page)
  const dialog = accountDialog(page)
  await dialog.getByRole('button', { name: 'Регистрация', exact: true }).click()
  await dialog.getByLabel('Имя', { exact: true }).fill('Айдана')
  await dialog.getByLabel('Email', { exact: true }).fill(`validation-${randomUUID()}@example.com`)
  await dialog.getByLabel('Пароль', { exact: true }).fill('short')
  await dialog.getByRole('button', { name: 'Создать аккаунт', exact: true }).click()
  await expect(dialog.getByText('В пароле должно быть не менее 15 символов.')).toBeVisible()
  await expect(dialog.getByLabel('Пароль', { exact: true })).toBeFocused()
  expect(registrationRequests).toBe(0)
  await dialog.getByRole('button', { name: 'Вход', exact: true }).click()
  await dialog.getByLabel('Пароль', { exact: true }).fill('a wrong password for a missing user')
  await dialog.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await expect(dialog.getByRole('heading', { name: 'С возвращением' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Войти в аккаунт' })).toBeFocused()
  await page.getByRole('button', { name: 'Подобрать подрядчиков', exact: true }).click()
  await expect(page.locator('.contractor-card')).toHaveCount(3)
})

test('диалог помещается на телефоне, удерживает фокус и сохраняет параметры подбора', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 640 })
  await page.goto('/')
  await page.getByLabel('Бюджет, ₸', { exact: true }).fill('1100000')
  await page.getByRole('button', { name: 'Войти в аккаунт' }).click()
  const dialog = accountDialog(page)
  await dialog.getByRole('button', { name: 'Регистрация', exact: true }).click()
  await dialog.getByLabel('Пароль', { exact: true }).fill(password)
  await dialog.getByRole('button', { name: 'Показать пароль' }).click()
  await expect(dialog.getByLabel('Пароль', { exact: true })).toHaveAttribute('type', 'text')
  await dialog.getByRole('button', { name: 'Скрыть пароль' }).click()
  for (let index = 0; index < 12; index++) {
    await page.keyboard.press('Tab')
    expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBeTruthy()
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBeTruthy()
  await page.screenshot({ path: '/tmp/ai-ana-account-320.png', fullPage: false })
  const createAccount = dialog.getByRole('button', { name: 'Создать аккаунт', exact: true })
  await createAccount.scrollIntoViewIfNeeded()
  await expect(createAccount).toBeVisible()
  await expect(createAccount).toBeInViewport()
  await page.screenshot({ path: '/tmp/ai-ana-account-320-submit.png', fullPage: false })
  await page.keyboard.press('Escape')
  await expect(page.getByLabel('Бюджет, ₸', { exact: true })).toHaveValue('1100000')
})

test('истёкшая сессия и сбой выхода не создают ложный успешный результат', async ({ page }) => {
  await openAccount(page)
  await register(page, `expiry-${randomUUID()}@example.com`)
  const dialog = accountDialog(page)
  await page.route('**/api/auth/logout', route => route.fulfill({ status: 503, json: { code: 'INTERNAL_ERROR', message: 'Сервер временно недоступен.', issues: [] } }), { times: 1 })
  await dialog.getByRole('button', { name: 'Выйти из аккаунта' }).click()
  await expect(dialog.getByRole('alert')).toHaveText('Сервер временно недоступен.')
  await expect(dialog.getByRole('heading', { name: 'Ваш профиль' })).toBeVisible()
  await page.route('**/api/auth/profile', route => route.fulfill({ status: 401, json: { code: 'UNAUTHENTICATED', message: 'Войдите в аккаунт.', issues: [] } }), { times: 1 })
  await dialog.getByLabel('Имя', { exact: true }).fill('Новое имя')
  await dialog.getByRole('button', { name: 'Сохранить изменения' }).click()
  await expect(dialog.getByRole('heading', { name: 'С возвращением' })).toBeVisible()
  await expect(dialog.getByRole('alert')).toHaveText('Сессия закончилась. Войдите снова, чтобы изменить профиль.')
  await expect(page.getByRole('button', { name: 'Войти в аккаунт', exact: true })).toBeAttached()
})
