"""Generate OpenAPI and TypeScript types from the actual server models, without HTTP."""
import json
from pathlib import Path
import re
from typing import Any

from .main import PROJECT_ROOT, app


def identifier(name: str) -> str:
    return re.sub(r'[^a-zA-Z0-9_]', '_', name)


def type_expression(schema: dict[str, Any]) -> str:
    if '$ref' in schema:
        return identifier(schema['$ref'].rsplit('/', 1)[1])
    if 'enum' in schema:
        return ' | '.join(json.dumps(value, ensure_ascii=False) for value in schema['enum'])
    if 'const' in schema:
        return json.dumps(schema['const'], ensure_ascii=False)
    if 'anyOf' in schema or 'oneOf' in schema:
        return '(' + ' | '.join(type_expression(item) for item in schema.get('anyOf', schema.get('oneOf'))) + ')'
    if 'allOf' in schema:
        return '(' + ' & '.join(type_expression(item) for item in schema['allOf']) + ')'
    kind = schema.get('type')
    if kind in ('integer', 'number'):
        return 'number'
    if kind == 'string':
        return 'string'
    if kind == 'boolean':
        return 'boolean'
    if kind == 'null':
        return 'null'
    if kind == 'array':
        return f'Array<{type_expression(schema.get("items", {}))}>'
    if kind == 'object':
        props = schema.get('properties', {})
        required = set(schema.get('required', []))
        fields = [f'  {json.dumps(name)}{"" if name in required else "?"}: {type_expression(value)};'
                  for name, value in props.items()]
        additional = schema.get('additionalProperties')
        if isinstance(additional, dict):
            fields.append(f'  [key: string]: {type_expression(additional)};')
        elif additional is True:
            fields.append('  [key: string]: unknown;')
        return '{\n' + '\n'.join(fields) + '\n}'
    if not schema:
        return 'unknown'
    raise ValueError(f'Неподдерживаемая схема: {schema}')


def main() -> None:
    document = app.openapi()
    (PROJECT_ROOT / 'docs' / 'openapi.json').write_text(json.dumps(document, ensure_ascii=False, indent=2) + '\n')
    declarations = ['// Generated by python -m app.export_contract. Do not edit by hand.',
                    '// Decimal output values are exact strings; input duration is a JSON number.']
    for name, schema in sorted(document['components']['schemas'].items()):
        declarations.append(f'export type {identifier(name)} = {type_expression(schema)};')
    target = PROJECT_ROOT / 'frontend' / 'src' / 'lib' / 'api' / 'generated.ts'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text('\n\n'.join(declarations) + '\n')
    print('Созданы docs/openapi.json и frontend/src/lib/api/generated.ts')


if __name__ == '__main__':
    main()
