import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowRight, ArrowUpRight, Check, ChevronDown, SlidersHorizontal, MapPin, CalendarDays, Search, RotateCcw, X, Info, Clock3 } from 'lucide-react'
import { Button } from './components/ui/button'
import { BrandLogo } from './components/brand/BrandLogo'

const categories = ['Ведущий', 'Фотограф', 'Банкетный зал', 'Ресторан', 'Лайв-бэнд', 'Шоу-программа', 'Видеограф', 'Загородная площадка', 'Национальный ансамбль', 'Танцевальный коллектив', 'Ведущий церемонии', 'Декоратор', 'Инструменталист', 'Отель', 'Подарки и сувениры', 'Флорист', 'Фото и видеобудки']
const formats = ['корпоратив', 'свадьба', 'той', 'конференция', 'юбилей', 'день рождения']
const schema = z.object({ city: z.enum(['Алматы', 'Астана', 'Зарубежье']), category: z.string().refine(v => categories.includes(v), 'Выберите категорию'), event_format: z.string().refine(v => formats.includes(v), 'Выберите формат'), event_date: z.string().refine(v => /^\d{4}-\d{2}-\d{2}$/.test(v) && Number.isFinite(Date.parse(v)) && new Date(v).toISOString().slice(0,10) === v && v >= '2026-09-23' && v <= '2026-12-31', 'Выберите дату с 23.09 по 31.12.2026'), budget_kzt: z.string().refine(v => /^\d+$/.test(v) && Number.isSafeInteger(Number(v)) && Number(v) > 0, 'Укажите положительный бюджет в целых тенге'), duration_hours: z.string().refine(v => v === '' || (Number.isFinite(Number(v)) && Number(v) > 0), 'Укажите длительность больше нуля'), language: z.enum(['', 'русский', 'казахский', 'английский']) })
type FormValues = z.infer<typeof schema>
const initial: FormValues = { city: 'Алматы', category: 'Ведущий', event_format: 'корпоратив', event_date: '2026-09-30', budget_kzt: '1000000', duration_hours: '', language: '' }
const demoCards = [
 { name: 'Александр · демо', initials: 'АЛ', price: '500 000', languages: 'Русский, казахский', hours: 'До 5 часов', description: 'В демонстрационном описании указаны командные игры и проведение награждений. Начальная цена 500 000 ₸ укладывается в бюджет примера — 1 000 000 ₸.', fact: 'Командные игры и награждения', tone: 'blue' },
 { name: 'Алия · демо', initials: 'АЛ', price: '650 000', languages: 'Русский, английский', hours: 'До 6 часов', description: 'В демонстрационном описании указано ведение деловой части и вечерней программы. Профиль поддерживает корпоратив, начальная цена — 650 000 ₸.', fact: 'Деловая и вечерняя программа', tone: 'purple' },
 { name: 'Данияр · демо', initials: 'ДА', price: '900 000', languages: 'Русский, казахский', hours: 'До 6 часов', description: 'В демонстрационном описании указана интерактивная программа с музыкальными конкурсами. Для примера на 30 сентября в календаре нет занятости.', fact: 'Музыкальные конкурсы', tone: 'sand' },
]
type Preview = 'cards' | 'initial' | 'empty' | 'unavailable' | 'error'
const presets = [['Синий', '#2563EB'], ['Зелёный', '#15803D'], ['Фиолетовый', '#7C3AED'], ['Оранжевый', '#C2410C']]
const validHex = (v: string) => /^#[\da-f]{6}$/i.test(v)
function getAccent() { try { const v = localStorage.getItem('ai-ana-accent'); return v && validHex(v) ? v : '#2563EB' } catch { return '#2563EB' } }
function onAccent(hex: string) { const rgb = [1,3,5].map(i => parseInt(hex.slice(i,i+2),16)/255).map(v => v <= .04045 ? v/12.92 : ((v+.055)/1.055)**2.4); return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722 > .179 ? '#000000' : '#FFFFFF' }

export default function App() {
 const [accent, setAccent] = useState(getAccent)
 const [hex, setHex] = useState(accent)
 const [appearance, setAppearance] = useState(false)
 const [preview, setPreview] = useState<Preview>('cards')
 const [loading, setLoading] = useState(false)
 const [submitted, setSubmitted] = useState(false)
 const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: initial })
 useEffect(() => { const root = document.documentElement; root.style.setProperty('--accent', accent); root.style.setProperty('--on-accent', onAccent(accent)); try { localStorage.setItem('ai-ana-accent',accent) } catch { /* Appearance remains available without storage. */ } }, [accent])
 useEffect(() => { if (!appearance) return; const close = (e: KeyboardEvent) => { if (e.key === 'Escape') setAppearance(false) }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown',close) }, [appearance])
 useEffect(() => { if (!loading) return; const timer = window.setTimeout(() => { setLoading(false); setSubmitted(true); setPreview('cards') }, 450); return () => clearTimeout(timer) }, [loading])
 const selectAccent = (v: string) => { setHex(v); if (validHex(v)) setAccent(v.toUpperCase()) }
 function field(name: keyof FormValues, label: string, children: React.ReactNode) { const error = form.formState.errors[name]; return <div className="field"><label htmlFor={name}>{label}</label>{children}{error && <p className="field-error" id={`${name}-error`}>{error.message}</p>}</div> }
 const attrs = (name: keyof FormValues) => ({ id: name, 'aria-invalid': !!form.formState.errors[name], 'aria-describedby': form.formState.errors[name] ? `${name}-error` : undefined, ...form.register(name) })
 return <><header className="site-header"><div className="header-inner"><BrandLogo/><div className="header-actions"><span className="header-location"><MapPin size={15}/> Казахстан</span><Button variant="outline" size="sm" aria-expanded={appearance} aria-controls="appearance" onClick={() => setAppearance(!appearance)}><SlidersHorizontal size={16}/> Оформление</Button></div></div></header>
 {appearance && <section className="appearance" id="appearance" aria-label="Настройки оформления"><div className="section-line"><h2>Ваш акцентный цвет</h2><Button variant="ghost" size="sm" aria-label="Закрыть настройки" onClick={() => setAppearance(false)}><X size={18}/></Button></div><p>Немного вашего стиля. Настройки сохраняются в этом браузере.</p><div className="swatches">{presets.map(([name,color]) => <button key={name} aria-pressed={accent.toLowerCase() === color.toLowerCase()} onClick={() => selectAccent(color)}><span style={{background:color}}/>{name}{accent.toLowerCase() === color.toLowerCase() && <Check size={14}/>}</button>)}</div><label className="hex-label" htmlFor="hex">Свой цвет</label><div className="color-inputs"><input type="color" aria-label="Выбрать акцентный цвет" value={accent} onChange={e => selectAccent(e.target.value)}/><input id="hex" value={hex} maxLength={7} onChange={e => selectAccent(e.target.value)} aria-invalid={!validHex(hex)} aria-describedby={!validHex(hex) ? 'hex-error' : undefined}/></div>{!validHex(hex) && <p id="hex-error" className="field-error">Введите цвет в формате #RRGGBB.</p>}<Button variant="ghost" size="sm" onClick={() => selectAccent('#2563EB')}><RotateCcw size={14}/> Вернуть стандартный цвет</Button></section>}
 <main className="page"><section className="hero"><div><div className="eyebrow"><span/> ПОДБОР ПОДРЯДЧИКОВ ДЛЯ СОБЫТИЙ</div><h1>Ваше событие.<br/><span>Подходящие люди.</span></h1><p>Расскажите о мероприятии — сравните до трёх вариантов<br className="desktop-break"/> и узнайте, почему каждый из них вам подходит.</p></div><div className="hero-note"><span className="note-number">01 — 03</span><span>Меньше поиска.<br/>Больше ясности в выборе.</span><ArrowUpRight size={24}/></div></section>
 <div className="demo-banner"><Info size={18}/><p><strong>Демонстрационный режим</strong><span>Вы смотрите прототип. Карточки вымышлены, реальный каталог ещё не подключён.</span></p><span className="demo-label">ПРЕВЬЮ</span></div>
 <div className="workspace"><aside className="form-panel"><div className="panel-heading"><span className="step">01</span><div><h2>О вашем событии</h2><p>Начнём с самого важного</p></div></div><form noValidate onSubmit={form.handleSubmit(() => { setLoading(true); setSubmitted(false) })}>
 <div className="form-fields">{field('city','Город',<select {...attrs('city')}>{['Алматы','Астана','Зарубежье'].map(v=><option key={v}>{v}</option>)}</select>)}
 {field('category','Кого ищем',<select {...attrs('category')}>{categories.map(v=><option key={v}>{v}</option>)}</select>)}
 <div className="field-row">{field('event_date','Дата события',<input type="date" min="2026-09-23" max="2026-12-31" {...attrs('event_date')}/>)}{field('event_format','Формат',<select {...attrs('event_format')}>{formats.map(v=><option key={v} value={v}>{v.charAt(0).toUpperCase()+v.slice(1)}</option>)}</select>)}</div>
 {field('budget_kzt','Бюджет, ₸',<input type="number" min="1" step="1" placeholder="Например, 1 000 000" {...attrs('budget_kzt')}/>)}<p className="input-hint">Сравниваем с начальной ценой за мероприятие</p>
 <div className="optional-heading"><span>Дополнительно</span><span>необязательно</span></div><div className="field-row">{field('duration_hours','Длительность, ч',<input type="number" min="0.5" step="0.5" placeholder="Не указана" {...attrs('duration_hours')}/>)}{field('language','Язык',<select {...attrs('language')}><option value="">Любой</option>{['русский','казахский','английский'].map(v=><option key={v} value={v}>{v.charAt(0).toUpperCase()+v.slice(1)}</option>)}</select>)}</div></div>
 <div className="form-bottom"><Button type="submit" className="w-full" disabled={loading}>{loading ? 'Загружаем пример…' : 'Посмотреть пример подбора'}<ArrowRight size={17}/></Button><p>Без заявок и бронирования.<br/>Только помощь с выбором.</p></div></form></aside>
 <section className="results" aria-label="Результат подбора"><div className="results-top"><div><div className="eyebrow small">ВАШ КОРОТКИЙ СПИСОК</div><h2>Есть из кого выбрать</h2></div><span className="result-counter">До 3 вариантов</span></div><div className="preview-controls" aria-label="Примеры состояний"><span>Посмотреть:</span>{([['cards','Карточки'],['empty','Нет подходящих'],['unavailable','Нет категории'],['initial','До поиска'],['error','Ошибка']] as const).map(([value,label])=><button key={value} disabled={loading} aria-pressed={preview===value} onClick={()=>{setPreview(value);setSubmitted(false)}}>{label}</button>)}</div>
 <div aria-live="polite" aria-busy={loading}>{loading ? <div className="empty-state"><Search size={28}/><h3>Открываем демонстрационный пример</h3><p>Реальный поиск пока не выполняется.</p></div> : preview==='cards' ? <><div className="result-summary"><span><Check size={15}/> Пример: показаны 3 из 6 подходящих</span><span>По начальной цене</span></div><p className="example-context">Фиксированный пример: Алматы · Ведущий · Корпоратив · 30 сентября 2026 · 1 000 000 ₸</p>{submitted && <p className="submission-note">Форма проверена. Ниже — фиксированные примеры оформления, они не рассчитаны по введённым условиям.</p>}<div className="cards">{demoCards.map((card,index)=><article className="contractor-card" key={card.name}><div className="card-top"><div className={`avatar ${card.tone}`} aria-hidden="true">{card.initials}</div><div className="identity"><span className="card-category">Ведущий <span> / 0{index+1}</span></span><h3>{card.name}</h3><span className="city"><MapPin size={13}/> Алматы</span></div><div className="price">от {card.price} <span>₸</span><small>за мероприятие</small></div></div><div className="card-attributes"><span><CalendarDays size={14}/> Свободен в примере на 30.09</span><span>{card.languages}</span><span><Clock3 size={14}/>{card.hours}</span></div><div className="explanation"><span className="explanation-label">Почему в этом примере</span><p>{card.description}</p></div><div className="card-bottom"><span className="synthetic">Синтетический демопрофиль</span><details><summary>Основания <ChevronDown size={14}/></summary><div className="evidence"><strong>Данные демонстрационной фикстуры</strong><p>Особенность: {card.fact}. Цена от {card.price} ₸. Формат: корпоратив. В календаре примера 30.09.2026 не занято.</p><p>Это вымышленные сведения для проверки интерфейса, не профиль из CSV.</p></div></details></div></article>)}</div><p className="result-footnote"><Info size={15}/> Начальная цена не является итоговой. Доступность в готовом сервисе будет проверяться по календарю датасета.</p></> : <div className="empty-state"><Search size={30}/><span className="eyebrow small">ПРИМЕР СОСТОЯНИЯ</span><h3>{preview==='initial'?'Начнём с вашего события':preview==='empty'?'По этим условиям нет подходящих':preview==='unavailable'?'В этом городе пока нет категории':'Не удалось загрузить подбор'}</h3><p>{preview==='initial'?'Заполните параметры слева, чтобы посмотреть, как будет выглядеть результат.':preview==='empty'?'В демонстрационной группе 10 профилей: 1 занят, 1 не поддерживает формат, 8 превышают бюджет. Каждый исключённый профиль учтён по одной основной причине.':preview==='unavailable'?'Пример: в каталоге нет декораторов в Астане. Можно самостоятельно выбрать другую категорию или город.':'Это пример технической ошибки. Он отличается от ситуации, когда подходящих подрядчиков нет.'}</p><Button variant="outline" onClick={()=>setPreview('cards')}>Вернуться к примеру карточек<ArrowRight size={15}/></Button></div>}</div></section></div>
 <section className="principles" aria-label="Как устроен выбор"><div><span>01 / УСЛОВИЯ</span><h3>Сначала — ваши параметры</h3><p>Город, дата и бюджет задают границы поиска.</p></div><div><span>02 / ПОНЯТНЫЙ ПОРЯДОК</span><h3>Цена, а не скрытый рейтинг</h3><p>Подходящие варианты — по начальной цене.</p></div><div><span>03 / ОБЪЯСНЕНИЯ</span><h3>У каждого выбора есть причина</h3><p>Конкретные факты вместо общих обещаний.</p></div></section>
 <footer><span>AI-ANA <span className="footer-separator">/</span> Событие начинается с выбора</span><span>Прототип для HackAlem · 2026</span></footer></main></>
}
